#ifndef CONFIGURATION_HPP
#define CONFIGURATION_HPP

const int NUMBER_OF_ADDRESS_BITS = 16;
const int NUMBER_OF_DISPLACEMENT_BITS = 8;
const int NUMBER_OF_PAGE_NUMBER_BITS = NUMBER_OF_ADDRESS_BITS - NUMBER_OF_DISPLACEMENT_BITS;
const int NUMBER_OF_FRAME_NUMBER_BITS = 8; // Change At The End...

const int MASK_FOR_ADDRESS = (1 << NUMBER_OF_ADDRESS_BITS) - 1;
const int MASK_FOR_DISPLACEMENT = (1 << NUMBER_OF_DISPLACEMENT_BITS) - 1;
const int MASK_FOR_PAGE_NUMBER = ((1 << NUMBER_OF_PAGE_NUMBER_BITS) - 1) << NUMBER_OF_DISPLACEMENT_BITS;

const int NUMBER_OF_TLB_ENTRIES = 16;

const int SIZE_OF_PAGE = 1 << NUMBER_OF_DISPLACEMENT_BITS;
const int SIZE_OF_FRAME = SIZE_OF_PAGE;

const int NUMBER_OF_PAGES = 1 << NUMBER_OF_PAGE_NUMBER_BITS;
const int NUMBER_OF_FRAMES = 1 << NUMBER_OF_FRAME_NUMBER_BITS;

#endif